error:
  whitelabel:
    enabled: false

amazon:
  associate_id: habuma-20

logging:
  level:
    root: DEBUG


spring:
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    platform: h2
  h2:
    console:
      enabled: true
      path: /h2-console